# FILES
defaults: # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade
  - train/data: distil_from_bm25
  - train/model: splade
  ############## INDEX ###################################
  - index: msmarco
  ############## RETRIEVE ################################
  - retrieve_evaluate: all
  ############### FLOPS ##################################
  - flops: msmarco

# Direct PARAMETER setting
config:
  loss: DistilMarginMSE
  regularizer:
    FLOPS:
      lambda_q: 0.5
      lambda_d: 0.4
      T: 50000
      targeted_rep: rep
      reg: FLOPS
  checkpoint_dir: models/mse_distil/checkpoint
  index_dir: models/mse_distil/index
  out_dir: models/mse_distil/out